[package]
name = "gltf"
version = "0.2.0"
authors = ["Alteous <alteous@outlook.com>"]
description = "glTF asset loader"
documentation = "https://docs.rs/gltf"
repository = "https://github.com/Alteous/gltf"
readme = "README.md"
keywords = ["glTF", "3D", "asset", "model", "scene"]
license = "MIT"
 
[dependencies]
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"

[[example]]
name = "box"
path = "examples/box/main.rs"

